C     COLUNA 1 COM 'C' OU '*' EH COMENTARIO
* ESTA LINHA TAMBEM EH UM COMENTARIO
      PROGRAM TESTE_LEXER

C     DECLARACOES (KEYWORDS E IDENTIFICADORES)
      INTEGER   VALOR1, _ID_INVALIDO, I
      REAL      X, Y, RESULTADO
      DOUBLE PRECISION DBL
      LOGICAL   FLAG
C     CHARACTER*10 TEXTO   <----- ver depois
      PARAMETER (MAX = 100)

C     CONSTANTES NUMERICAS (INTEGER, REAL, SCIENTIFIC, DOUBLE)
      VALOR1 = 123
      X = 45.67
      Y = .89
      RESULTADO = 1.2E-3
      DBL = 3.14159D0

C      OPERADORES LOGICOS (TOKENS ESPECIAIS COM PONTOS)
      FLAG = .TRUE.
      IF (VALOR1 .GT. 100 .AND. .NOT. FLAG) THEN
          FLAG = .FALSE.
      ENDIF

C     OPERADORES ARITMETICOS E DE STRING
      X = (Y * 2.0) / (VALOR1 + 5) - 0.5
      X = 2.0 ** 3.0
      TEXTO = 'OLA' // 'MUNDO'

C     CONTINUACAO DE LINHA (CARACTERE NA COLUNA 6)
      IF (X .EQ. 
     +    Y) THEN
          PRINT *, 'X E Y SAO IGUAIS'
C         WRITE(*,*) 'IGUAL'     <----- ver depois
      ENDIF

C     LABELS (NUMEROS NAS COLUNAS 1-5) E LOOP DO
      DO 100 I = 1, 10
          IF (I .LE. 5) GOTO 100
          PRINT *, 'VALOR DE I:', I
  100 CONTINUE

C     STRINGS COM ASPAS SIMPLES E CARACTERES ESPECIAIS
C     WRITE(*, '(A)') 'TESTE DE "ASPAS" E @#$%&*!'            <----- ver depois

      STOP
      END